#!/usr/bin/env python
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/
from __future__ import division, absolute_import, print_function, unicode_literals
import OpenSSL
import uuid
import random
import os
import json
import subprocess
import sys
import time
import signal
if sys.version_info[:1] == (2,):
    input = raw_input

DIR_CNF     = '/etc/openvpn/'
DIR_TMPL    = DIR_CNF+'gen/templates/'
DIR_CLI     = DIR_CNF+'clients/'

FILE_CACRT  = DIR_CNF+'ca.crt'
FILE_CAKEY  = DIR_CNF+'ca.key'
FILE_SRVCRT = DIR_CNF+'server.crt'
FILE_SRVKEY = DIR_CNF+'server.key'
FILE_DHPEM  = DIR_CNF+'dh.pem'
FILE_SRVCNF = DIR_CNF+'server.conf'
FILE_CLIKEY = DIR_CLI+'null.key'
FILE_CLICRT = DIR_CLI+'null.crt'
FILE_CLICNF = "null"

WAIT_CONT = 0.8

null = open('/dev/null','w')

def clear():
    """
    Clears the screen if run from a TTY
    """
    if os.isatty(sys.stdin.fileno()):
        os.system('clear')

def sigint_handle(signal, frame):
    clear()
    print('Operation Cancelled!')
    sys.exit(0)
signal.signal(signal.SIGINT, sigint_handle)


def create_ca(size=4096, valid=315360000, CN=None):
    """
    Creates a CA key and cert

    size - The RSA key size to be used
    valid - The time is seconds the key should be valid for
    CN - The CN to be used for the cert. None will create a UUID
    """
    if CN is None:
        CN = 'CA-'+str(uuid.uuid4())
    key = OpenSSL.crypto.PKey()
    clear()
    print('Generating Certificate Authority Key...')
    start = time.time()
    key.generate_key(OpenSSL.crypto.TYPE_RSA, size)
    end = time.time()
    print('Took '+str(end - start)+' seconds')
    time.sleep(WAIT_CONT)

    ca = OpenSSL.crypto.X509()
    ca.set_version(2)
    #ca.set_serial_number(1)
    ca.get_subject().CN = CN
    ca.gmtime_adj_notBefore(0)
    ca.gmtime_adj_notAfter(valid)
    ca.set_issuer(ca.get_subject())
    ca.set_pubkey(key)
    ca.add_extensions([
        OpenSSL.crypto.X509Extension(b"basicConstraints", False, b"CA:TRUE"),
        OpenSSL.crypto.X509Extension(b"keyUsage", False, b"keyCertSign, cRLSign"),
        OpenSSL.crypto.X509Extension(b"subjectKeyIdentifier", False, b"hash", subject=ca)
    ])
    ca.add_extensions([
        OpenSSL.crypto.X509Extension(b"authorityKeyIdentifier", False, b"keyid:always",issuer=ca)
    ])

    clear()
    print('Signing Key...')
    start = time.time()
    ca.sign(key, b"sha256")
    end = time.time()
    print('Took '+str(end - start)+' seconds')
    time.sleep(WAIT_CONT)

    return ca, key

def create_cert(is_server, cacert, cakey, size=4096, valid=315360000, CN=None):
    """
    Creates a client/server key and cert

    is_server - Must be True for a server, False for a client
    cacert - The OpenSSL.crypto.X509 object of the CA
    cakey - The OpenSSL.crypto.PKey object of the CA

    Optional:
    size - The RSA key size to be used
    valid - The time is seconds the key should be valid for
    CN - The CN to be used for the cert. None will create a UUID
    """
    if CN is None:
        if is_server:
            CN='server-'+str(uuid.uuid4())
        else:
            CN = 'client-'+str(uuid.uuid4())
    key = OpenSSL.crypto.PKey()
    clear()
    if is_server:
        print('Generating Server Key...')
    else:
        print('Generating Client Key...')
    start = time.time()
    key.generate_key(OpenSSL.crypto.TYPE_RSA, size)
    end = time.time()
    print('Took '+str(end - start)+' seconds')
    time.sleep(WAIT_CONT)

    cert = OpenSSL.crypto.X509()
    cert.set_version(2)
    cert.set_serial_number(random.randint(1, 99999999))
    cert.get_subject().CN = CN
    cert.gmtime_adj_notBefore(0)
    cert.gmtime_adj_notAfter(valid)
    cert.set_issuer(cacert.get_subject())
    cert.set_pubkey(key)
    if is_server:
        cert.add_extensions([
            OpenSSL.crypto.X509Extension(b"basicConstraints", False, b"CA:FALSE"),
            OpenSSL.crypto.X509Extension(b"keyUsage", False, b"digitalSignature,keyEncipherment"),
            OpenSSL.crypto.X509Extension(b"extendedKeyUsage", False, b"serverAuth"),
            OpenSSL.crypto.X509Extension(b"subjectKeyIdentifier", False, b"hash", subject=cert),
            OpenSSL.crypto.X509Extension(b"authorityKeyIdentifier", False, b"keyid:always",issuer=cacert),
            OpenSSL.crypto.X509Extension(b"nsCertType", False, b"server")
        ])
    else:
        cert.add_extensions([
            OpenSSL.crypto.X509Extension(b"basicConstraints", False, b"CA:FALSE"),
            OpenSSL.crypto.X509Extension(b"keyUsage", False, b"digitalSignature"),
            OpenSSL.crypto.X509Extension(b"extendedKeyUsage", False, b"clientAuth"),
            OpenSSL.crypto.X509Extension(b"subjectKeyIdentifier", False, b"hash", subject=cert),
            OpenSSL.crypto.X509Extension(b"authorityKeyIdentifier", False, b"keyid:always",issuer=cacert),
            OpenSSL.crypto.X509Extension(b"nsCertType", False, b"client")
        ])
    clear()
    print('Signing Key...')
    start = time.time()
    cert.sign(cakey, b"sha256")
    end = time.time()
    print('Took '+str(end - start)+' seconds')
    time.sleep(WAIT_CONT)

    return cert, key

def gen_dhparams(size=4096):
    """
    Generate Diffie Hellman parameters by calling openssl. Returns a string.

    I don't like doing it like this but pyopenssl doesn't seem to
    have a way to do this natively.

    size - The size of the prime to generate.
    """

    if not os.path.isfile(FILE_DHPEM):
        cmd = ['openssl', 'dhparam', '-out', FILE_DHPEM, str(size)]
        try:
            clear()
            print('Generating DH Key...')
            start = time.time()
            subprocess.check_call(cmd, stdout=null, stderr=null)
            end = time.time()
            print('Took '+str(end - start)+' seconds')
            time.sleep(WAIT_CONT)
        except subprocess.CalledProcessError:
            # Sometimes we get a non-zero exit code, no idea why...
            print('Calling of openssl failed... Trying again')
            start = time.time()
            subprocess.check_call(cmd, stdout=null, stderr=null)
            end = time.time()
            print('Took '+str(end - start)+' seconds')
            time.sleep(WAIT_CONT)

    with open(FILE_DHPEM) as dh:
        params = dh.read()
    return params

def gen_tlsauth_key():
    """Generate an openvpn secret key by calling openvpn. Returns a string."""
    if not os.path.isfile(DIR_CNF+'ta.pem'):
        print('Generating TLS Auth Key...')
        start = time.time()
        cmd = ['openvpn', '--genkey', '--secret', DIR_CNF+'ta.pem']
        ret = subprocess.check_call(cmd, stdout=null, stderr=null)
        end = time.time()
        print('Took '+str(end - start)+' seconds')
        time.sleep(WAIT_CONT)

    with open(DIR_CNF+'ta.pem') as key:
        key = key.read()
    return key

def _create_server_conf(name, confdict, port, cacert, serverkey, servercert, tls_auth=True):
    clear()
    print('Generating Server Configs...')
    start = time.time()
    serverfile = open(FILE_SRVCNF, 'w')

    for key, value in confdict['both'].items():
        if value is False:
            continue
        elif value is True:
            serverfile.write(key + '\n')
        elif isinstance(value, list):
            for v in value:
                serverfile.write(key + ' ' + v + '\n')
        else:
            serverfile.write(key + ' ' + value + '\n')

    for key, value in confdict['server'].items():
        if value is False:
            continue
        elif value is True:
            serverfile.write(key + '\n')
        elif isinstance(value, list):
            for v in value:
                serverfile.write(key + ' ' + v + '\n')
        else:
            serverfile.write(key + ' ' + value + '\n')

    serverfile.write('port ' + port + '\n')

    if 'meta' in confdict:
        if confdict['meta'].get('embedkeys', True):
            serverfile.write('<ca>\n'+cacert+'</ca>\n')
            serverfile.write('<key>\n'+serverkey+'</key>\n')
            serverfile.write('<cert>\n'+servercert+'</cert>\n')
            serverfile.write('<dh>\n'+gen_dhparams()+'</dh>\n')
        if tls_auth is not False:
            serverfile.write('key-direction 0\n')
            serverfile.write('<tls-auth>\n'+tls_auth+'</tls-auth>\n')
    end = time.time()
    print('Took '+str(end - start)+' seconds')
    time.sleep(WAIT_CONT)

def _create_client_conf(name, confdict, host, port, cacert, clientkey, clientcert, tls_auth=True):
    clear()
    print('Generating Client Configs...')
    start = time.time()
    try:
        if FILE_CLICNF == "null":
            FILE_CLICNF = DIR_CLI+name+'.ovpn'
    except UnboundLocalError:
        FILE_CLICNF = DIR_CLI+name+'.ovpn'
    clientfile = open(FILE_CLICNF, 'w')

    clientfile.write('client\n')
    clientfile.write('remote ' + host + ' ' + port + '\n')

    for key, value in confdict['both'].items():
        if value is False:
            continue
        elif value is True:
            clientfile.write(key + '\n')
        elif isinstance(value, list):
            for v in value:
                clientfile.write(key + ' ' + v + '\n')
        else:
            clientfile.write(key + ' ' + value + '\n')

    for key, value in confdict['client'].items():
        if value is False:
            continue
        elif value is True:
            clientfile.write(key + '\n')
        elif isinstance(value, list):
            for v in value:
                clientfile.write(key + ' ' + v + '\n')
        else:
            clientfile.write(key + ' ' + value + '\n')

    if 'meta' in confdict:
        if confdict['meta'].get('embedkeys', True):
            clientfile.write('<ca>\n'+cacert+'</ca>\n')
            clientfile.write('<key>\n'+clientkey+'</key>\n')
            clientfile.write('<cert>\n'+clientcert+'</cert>\n')
        if tls_auth is not False:
            clientfile.write('key-direction 1\n')
            clientfile.write('<tls-auth>\n'+tls_auth+'</tls-auth>\n')
    end = time.time()
    print('Took '+str(end - start)+' seconds')
    time.sleep(WAIT_CONT)

def create_confs(name, confdict):
    """
    Creates the client and server configs.

    name - The name of the run which is prepended to the config file names
    confdict - A dictionary representing the config parameters.
    """

    FILE_CLIKEY = DIR_CLI+name+'.key'
    FILE_CLICRT = DIR_CLI+name+'.crt'
    FILE_CLICNF = DIR_CLI+name+'.ovpn'

    tls_auth = True
    if 'meta' in confdict:
        if confdict['meta'].get('tls-auth', True):
            tls_auth = gen_tlsauth_key()
        host = confdict['meta'].get('host', "localhost")
        port = confdict['meta'].get('port', "443")
    else:
        host = "localhost"
        port = "443"

    # Create CA
    if os.path.isfile(FILE_CACRT) and os.path.isfile(FILE_CAKEY):
        cacert = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, open(FILE_CACRT, 'rt').read())
        cakey = OpenSSL.crypto.load_privatekey(OpenSSL.crypto.FILETYPE_PEM, open(FILE_CAKEY,'rt').read())
    else:
        cacert, cakey = create_ca()

    text_cacert = OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cacert).decode('ascii')
    text_cakey = OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, cakey).decode('ascii')

    # Create a server
    if os.path.isfile(FILE_SRVCRT) and os.path.isfile(FILE_SRVKEY):
        servercert = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, open(FILE_SRVCRT, 'rt').read())
        serverkey = OpenSSL.crypto.load_privatekey(OpenSSL.crypto.FILETYPE_PEM, open(FILE_SRVKEY,'rt').read())
    else:
        servercert, serverkey = create_cert(True, cacert, cakey)

    serverkey = OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, serverkey).decode('ascii')
    servercert = OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, servercert).decode('ascii')
    _create_server_conf(name, confdict, port, text_cacert, serverkey, servercert, tls_auth=tls_auth)

    # Create a client
    clientcert, clientkey = create_cert(False, cacert, cakey)
    clientkey = OpenSSL.crypto.dump_privatekey(OpenSSL.crypto.FILETYPE_PEM, clientkey).decode('ascii')
    clientcert = OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, clientcert).decode('ascii')
    _create_client_conf(name, confdict, host, port, text_cacert, clientkey, clientcert, tls_auth=tls_auth)

    try:
        with open(FILE_CLICRT, 'w') as fileout:
             fileout.write(clientcert)
    except Exception as e:
        print('Unable to write', FILE_CLICRT)
        print(e)
    try:
        with open(FILE_CLIKEY, 'w') as fileout:
             fileout.write(clientkey)
    except Exception as e:
        print('Unable to write', FILE_CLIKEY)
        print(e)
    try:
        with open(FILE_SRVCRT, 'w') as fileout:
             fileout.write(servercert)
    except Exception as e:
        print('Unable to write', FILE_SRVCRT)
        print(e)
    try:
        with open(FILE_SRVKEY, 'w') as fileout:
             fileout.write(serverkey)
    except Exception as e:
        print('Unable to write', FILE_SRVKEY)
        print(e)
    try:
        with open(FILE_CACRT, 'w') as fileout:
             fileout.write(text_cacert)
    except Exception as e:
        print('Unable to write', FILE_CACRT)
        print(e)
    try:
        with open(FILE_CAKEY, 'w') as fileout:
             fileout.write(text_cakey)
    except Exception as e:
        print('Unable to write', FILE_CAKEY)
        print(e)

def _parse_args():
    """Parse command line args"""
    import argparse
    parser = argparse.ArgumentParser(description='Generate OpenVPN configs through templates')
    parser.add_argument('-t', '--template', required=False, help='Template or template directory to use', default=DIR_TMPL)
    parser.add_argument('-n', '--name'    , required=True , help='Name of client')
    return parser.parse_args()

def _ask_template(templates,ret=None):
    """Prompts user for the template to use"""
    i = 1
    if ret is None:
        print('Which template would you like to use?')
        for template in templates:
            print(i, ') ', template['meta']['name'], ': ', template['meta']['description'],sep='')
            i += 1
            ret = int(input('Enter selection: '))
        while ret <= 0 or ret > i-1:
            ret = int(input('Enter selection: '))
        return templates[ret-1]
    else:
        try:
            i = int(ret) - 1
            return templates[i]
        except ValueError:
            for template in templates:
                if ret == template['meta']['name']:
                    return template
def main():
    clear()
    args = _parse_args()

    # Read in configs
    confs = []
    if os.path.isdir(args.template):
        list = os.listdir(args.template)
        for f in list:
            f = os.path.join(args.template, f)
            if os.path.isfile(f):
                with open(f, 'r') as fh:
                    try:
                        data = json.loads(fh.read())
                    except Exception as e:
                        print('WARNING:', f, 'is not valid json.', e, file=sys.stderr)
                        continue
                if 'meta' in data:
                    if 'name' not in data['meta']:
                        data['meta']['name'] = f
                    if 'description' not in data['meta']:
                        data['meta']['description'] = ''
                confs.append(data)
    elif os.path.isfile(args.template):
        with open(args.template, 'r') as fh:
            try:
                confs.append(json.loads(fh.readall()))
            except Exception as e:
                print('WARNING:', args.template, 'is not valid json.', e, file=sys.stderr)
    else:
        tmplst = []
        list = os.listdir(DIR_TMPL)
        for f in list:
            f = os.path.join(DIR_TMPL, f)
            if os.path.isfile(f):
                with open(f, 'r') as fh:
                    try:
                        data = json.loads(fh.read())
                    except Exception as e:
                        print('WARNING:', f, 'is not valid json.', e, file=sys.stderr)
                        continue
                if 'meta' in data:
                    if 'name' not in data['meta']:
                        data['meta']['name'] = f
                    if 'description' not in data['meta']:
                        data['meta']['description'] = ''
                tmplst.append(data)
        confs.append(_ask_template(tmplst,args.template))

    if len(confs) == 0:
        print('ERROR: No valid templates to use', file=sys.stderr)
        exit(-1)
    elif len(confs) == 1:
        template = confs[0]
    else:
        template = _ask_template(confs)

    name = args.name
    create_confs(name, template)
    clear()
    print('DynaGen Cycle Complete!')
if __name__ == "__main__":
    main()
